import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// We can create the different layouts based on different route groups as well.
export const metadata: Metadata = {
  title: {
    default: "Technical Agency Marketing",
    template: "%s | Technical Agency",
    // Absolute can be used to override the template as well.
    absolute: "Tech Agency",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
