import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata used for showing some extra data and we do not need to add it simply inside the head tag. We can also add metadata for all the different files by putting the metadata inside the page.tsx file itself and it can be different title for different page components. Also we can set the object to the title and provide the default value and provide the template.
export const metadata: Metadata = {
  title: {
    default: "Technical Agency",
    template: "%s | Technical Agency",
    // Absolute can be used to override the template as well.
    absolute: "Tech Agency",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
